import QtQuick 6.7

QtObject {
    readonly property var chromeMetrics: ({ frameScale: 0.60, compactFrameScale: 0.24, titleHeight: 66, compactTitleHeight: 30, leftInset: 108, compactLeftInset: 43, rightInset: 22, compactRightInset: 9, bottomInset: 96, compactBottomInset: 39, sidebarHeaderHeight: 76, compactSidebarHeaderHeight: 60, windowButtonsTopInset: 3, compactWindowButtonsTopInset: 0, windowButtonsHeight: 30, compactWindowButtonsIconLift: 8 })
    readonly property string titleBarContentComponentFile: "../themes/rx93/Rx93TitleContent.qml"
    readonly property string name: "RX-93 Psycho-Frame"
    readonly property bool supporterOnly: false
    readonly property bool terminalMode: false
    readonly property bool classicMode: false
    readonly property bool iconGlyphsVisible: true
    readonly property string iconFolder: "themes/rx93-psycho-frame/icons"
    readonly property bool iconColorize: true
    readonly property color iconTint: "#dce6df"
    readonly property string uiFontFile: "themes/rx93-psycho-frame/fonts/Barlow-Medium.ttf"
    readonly property string displayFontFile: "themes/rx93-psycho-frame/fonts/BarlowSemiCondensed-SemiBold.ttf"
    readonly property string monoFontFile: ""
    readonly property string backdropComponentFile: "../themes/rx93/Rx93Backdrop.qml"
    readonly property string foregroundComponentFile: "../themes/rx93/Rx93Foreground.qml"
    readonly property string pageTransitionComponentFile: "../themes/rx93/Rx93PageTransition.qml"
    readonly property bool equipmentAccentsEnabled: false
    readonly property bool ambientScanEnabled: false
    readonly property bool controlSignalEnabled: false
    readonly property bool navSignalEnabled: false
    readonly property bool panelLocatorEnabled: false
    readonly property bool headerSignalEnabled: false
    readonly property bool angularControlsEnabled: false
    readonly property real angularCutSize: 0
    readonly property real angularNotchSize: 0
    readonly property real angularPanelCutSize: 0
    readonly property real angularStrokeWidth: 1
    readonly property bool glitchInteractionsEnabled: false
    readonly property real glitchIntensity: 0
    readonly property bool diagnosticEasterEggsEnabled: false
    readonly property bool technicalTypographyEnabled: false
    readonly property bool floatingPanelsEnabled: false
    readonly property bool glyphRailsEnabled: false
    readonly property string logoDialFile: ""
    readonly property real logoDialOpacity: 0
    readonly property bool logoColorize: false
    readonly property color logoTint: "#e5ece3"
    readonly property color signalPrimary: "#91d9b4"
    readonly property color signalSecondary: "#d9b868"
    readonly property color signalDanger: "#d75951"
    readonly property color signalSuccess: "#91d9b4"
    readonly property color signalOff: "#35453c"
    readonly property color transitionSweep: "#d9b868"
    readonly property color transitionTrail: "#83c9a7"
    readonly property real interactionSweepDuration: 160
    readonly property real interactionSweepWidth: 0
    readonly property real pageTransitionDuration: 240
    readonly property real locatorOpacity: 0
    readonly property color backgroundA: "#10151d"
    readonly property color backgroundB: "#18222e"
    readonly property color backgroundC: "#243244"
    readonly property color surface: "#ee19232e"
    readonly property color surfaceSoft: "#ee131c26"
    readonly property color surfaceStrong: "#ff202c39"
    readonly property color surfaceRaised: "#ff293747"
    readonly property color surfaceTop: "#ff293747"
    readonly property color surfaceBottom: "#ff151f2a"
    readonly property color surfaceStrongTop: "#ff2c3949"
    readonly property color surfaceStrongBottom: "#ff1a2633"
    readonly property color border: "#5c6c7d"
    readonly property color borderSoft: "#758595"
    readonly property color borderStrong: "#a8b3c0"
    readonly property color divider: "#4b5e70"
    readonly property color text: "#eff2f6"
    readonly property color muted: "#cbd3df"
    readonly property color subtle: "#aebccb"
    readonly property color faint: "#9baaba"
    readonly property color primary: "#a1ecc9"
    readonly property color primaryBright: "#c7f5df"
    readonly property color primaryHot: "#e6bb50"
    readonly property color primaryDeep: "#244838"
    readonly property color primarySoft: "#385ea983"
    readonly property color hover: "#258bc7a4"
    readonly property color success: "#95ddb3"
    readonly property color warning: "#e9bc61"
    readonly property color danger: "#ff8585"
    readonly property color updateAlertSurface: "#b63f3b"
    readonly property color updateAlertText: "#ffffff"
    readonly property color classificationHandmade: "#efc984"
    readonly property color classificationToolmade: "#8ecdc6"
    readonly property color consoleBackground: "#f30c1112"
    readonly property color shadow: "#b3000000"
    readonly property color innerHighlight: "#41839587"
    readonly property color focusColor: "#d9b868"
    readonly property color primaryText: "#121c2a"
    readonly property color appBorder: "#334353"
    readonly property color titleBarSurface: "#00000000"
    readonly property color titleBarButtonHover: "#70677685"
    readonly property color titleBarCloseHover: "#9b3936"
    readonly property color logoCapsuleSurface: "#0c1415"
    readonly property color panelTop: "#ff283543"
    readonly property color panelMiddle: "#ff1d2935"
    readonly property color panelBottom: "#ff15212d"
    readonly property color panelSoftTop: "#ff243240"
    readonly property color panelSoftMiddle: "#ff1c2834"
    readonly property color panelSoftBottom: "#ff16212d"
    readonly property color panelStrongTop: "#ff2b3846"
    readonly property color panelStrongMiddle: "#ff21303f"
    readonly property color panelStrongBottom: "#ff192735"
    readonly property color panelTopHighlight: "#638b9891"
    readonly property color panelInnerBorder: "#324b5c52"
    readonly property color panelStrongInnerBorder: "#72778172"
    readonly property color panelOverlay: "#03121212"
    readonly property color panelStrongOverlay: "#05121212"
    readonly property color panelGlowShadow: "#234cd598"
    readonly property color panelConvexLeftHighlight: "#007b978c"
    readonly property color panelConvexRightShadow: "#00000000"
    readonly property color panelConvexBottomShadow: "#00000000"
    readonly property color panelConvexCenterGlow: "#00000000"
    readonly property real panelNoiseSoftOpacity: 0
    readonly property real panelNoiseOpacity: 0
    readonly property real panelNoiseStrongOpacity: 0
    readonly property real panelHighlightSoftOpacity: 0
    readonly property real panelHighlightOpacity: 0
    readonly property real panelHighlightStrongOpacity: 0
    readonly property real panelOverlaySoftOpacity: 0
    readonly property real panelOverlayOpacity: 0
    readonly property color primaryButtonBorder: "#94a39d"
    readonly property color primaryButtonHoverBorder: "#d4e9dc"
    readonly property color primaryButtonTop: "#eff0e9"
    readonly property color primaryButtonMiddle: "#d8ddd7"
    readonly property color primaryButtonBottom: "#a6b4aa"
    readonly property color primaryButtonHoverTop: "#f7faf6"
    readonly property color primaryButtonHoverMiddle: "#edf3ed"
    readonly property color primaryButtonHoverBottom: "#c5d6c9"
    readonly property color primaryButtonShadow: "#a3000000"
    readonly property color primaryButtonHoverShadow: "#343bc486"
    readonly property color primaryButtonSheenTransparent: "#00ffffff"
    readonly property color primaryButtonSheen: "#00000000"
    readonly property color primaryButtonLip: "#344740"
    readonly property color primaryButtonLipPressed: "#15221c"
    readonly property color primaryButtonGlassTop: "#00000000"
    readonly property color primaryButtonGlassMiddle: "#00000000"
    readonly property color primaryButtonInnerShadow: "#00000000"
    readonly property string primaryButtonTextureFile: ""
    readonly property real primaryButtonTextureOpacity: 0
    readonly property string primaryButtonLensOverlayFile: ""
    readonly property real primaryButtonLensOverlayOpacity: 0
    readonly property color primaryButtonText: "#121c2a"
    readonly property real buttonGlassBackdropOpacity: 0
    readonly property real buttonGlassBackdropBlur: 0
    readonly property int buttonGlassBackdropBlurMax: 0
    readonly property real buttonGlassBackdropBlurMultiplier: 0
    readonly property real buttonGlassBackdropBrightness: 0
    readonly property real buttonGlassBackdropContrast: 0
    readonly property real buttonGlassBackdropSaturation: 1
    readonly property real buttonGlassBackdropDownsample: 1
    readonly property real buttonGlassLensOpacity: 0
    readonly property real buttonGlassLensInsetX: 0
    readonly property real buttonGlassLensInsetY: 0
    readonly property real buttonGlassLensOffsetX: 0
    readonly property real buttonGlassLensOffsetY: 0
    readonly property real buttonGlassLensBlur: 0
    readonly property real buttonGlassLensContrast: 0
    readonly property real buttonGlassLensSaturation: 1
    readonly property color buttonGlassLensLeftHighlight: "#00ffffff"
    readonly property color buttonGlassLensCenterHighlight: "#00ffffff"
    readonly property color buttonGlassLensRightShadow: "#00000000"
    readonly property color ghostSurface: "#272f30"
    readonly property color ghostHoverSurface: "#384640"
    readonly property color ghostPressedSurface: "#1b3027"
    readonly property color ghostShadow: "#00000000"
    readonly property color fieldSurface: "#ff101923"
    readonly property color fieldHoverSurface: "#ff1b2a39"
    readonly property color fieldFocusSurface: "#ff23394a"
    readonly property color comboSurfaceOpen: "#223344"
    readonly property color comboHoverSurface: "#314456"
    readonly property color comboPopupSurface: "#17232f"
    readonly property color comboHighlight: "#d0dbe5"
    readonly property color checkboxSurface: "#131e2b"
    readonly property color checkboxHoverSurface: "#2a4154"
    readonly property color checkboxCheckedSurface: "#a6edd0"
    readonly property color switchTrackOff: "#46596b"
    readonly property color sliderTrack: "#6f8193"
    readonly property color navHoverSurface: "#263d53"
    readonly property color navActiveGlow: "#004bc489"
    readonly property color navActiveTop: "#233f31"
    readonly property color navActiveMiddle: "#233f31"
    readonly property color navActiveBottom: "#162d24"
    readonly property color rowHover: "#443c536b"
    readonly property color rowSelectedSurface: "#7042576e"
    readonly property color previewSurface: "#151e29"
    readonly property color previewSurfaceSoft: "#111a24"
    readonly property color helpCategorySelected: "#a6bca5"
    readonly property color helpCategoryHover: "#293e51"
    readonly property color helpCategorySurface: "#1a2938"
    readonly property color helpBadgeSelected: "#d8e6dc"
    readonly property color helpBadge: "#293f53"
    readonly property color helpBadgeBorder: "#689781"
    readonly property color helpTopicSelected: "#c0cfbb"
    readonly property color helpTopicHover: "#2b4054"
    readonly property color helpTopicSurface: "#1b2a39"
    readonly property color stepBadge: "#304d3c"
    readonly property color richAccent: "#b8ecd0"
    readonly property color backdropOverlayTop: "#00000000"
    readonly property color backdropOverlayMiddle: "#08101416"
    readonly property color backdropOverlayBottom: "#19101416"
    readonly property string backdropBaseFile: ""
    readonly property string backdropBranchTopFile: ""
    readonly property string backdropBranchBottomFile: ""
    readonly property string backdropPetalFile: ""
    readonly property string panelNoiseFile: ""
    readonly property string panelGlintFile: ""
    readonly property string panelRefractionFile: ""
    readonly property real panelRefractionOpacity: 0
    readonly property string panelEdgeFile: ""
    readonly property real panelEdgeOpacity: 0
    readonly property bool customFrameExclusive: true
    readonly property real customFrameRadius: 3
    readonly property string goldTrimFile: ""
    readonly property real goldTrimOpacity: 0
    readonly property bool glassBackdropEnabled: false
    readonly property real glassBackdropOpacity: 0
    readonly property real glassBackdropBlur: 0
    readonly property int glassBackdropBlurMax: 0
    readonly property real glassBackdropBlurMultiplier: 0
    readonly property real glassBackdropBrightness: 0
    readonly property real glassBackdropContrast: 0
    readonly property real glassBackdropSaturation: 1
    readonly property real glassBackdropDownsample: 1
    readonly property string logoFile: "themes/rx93-psycho-frame/rx93-mark.svg"
    readonly property bool backdropBranchesVisible: false
    readonly property bool backdropPetalsVisible: false
    readonly property real backdropTopBranchOpacity: 0
    readonly property real backdropBottomBranchOpacity: 0
    readonly property real sidebarBranchOpacity: 0
    readonly property real sidebarCompactBranchOpacity: 0
    readonly property bool supporterSignatureVisible: false
    readonly property string supporterSignatureText: ""
    readonly property string controlSurfaceComponentFile: "../themes/rx93/Rx93ControlSurface.qml"
    readonly property string panelSurfaceComponentFile: "../themes/rx93/Rx93PanelSurface.qml"
    readonly property string sidebarSurfaceComponentFile: "../themes/rx93/Rx93SidebarSurface.qml"
    readonly property string sidebarHeaderComponentFile: "../themes/rx93/Rx93SidebarHeader.qml"
}
