"""Maintain the editor's English/Korean catalogs and offline browser packs."""
from __future__ import annotations

import argparse
import ast
from collections import Counter
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import sys

HERE = Path(__file__).resolve().parent
EDITOR = HERE.parent
ROOT = EDITOR.parents[1]
sys.path.insert(0, str(ROOT))
from tools.editor_manifest import load_manifest, native_source
LANGUAGES = ("en", "ko")
SECTIONS = ("messages", "html", "families", "shapeLabels")
JS_REFERENCE = re.compile(r'(?:KfpsI18n\.(?:t|term)|\btr)\(\s*("(?:\\.|[^"\\])*")')


def read_catalog(language):
    def unique_keys(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"Duplicate key in {language}.json: {key!r}")
            result[key] = value
        return result
    return json.loads((HERE / f"{language}.json").read_text(encoding="utf-8"), object_pairs_hook=unique_keys)


def write_catalog(language, catalog):
    (HERE / f"{language}.json").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def pack(language, catalog):
    data = json.dumps(catalog, ensure_ascii=False, indent=2)
    return ("// Generated by locales/manage.py build. Edit the JSON catalog, not this file.\n"
            "window.KfpsEditorLocales = window.KfpsEditorLocales || {};\n"
            f"window.KfpsEditorLocales.{language} = {data};\n")


class StaticMessages(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.keys = set()
        self.stack = []

    def add(self, text):
        key = re.sub(r"\s+", " ", text).strip()
        if re.search(r"[A-Za-z]", key):
            self.keys.add(key)

    def handle_starttag(self, tag, attrs):
        attributes = dict(attrs)
        blocked = (tag in ("script", "style", "textarea", "kbd")
                   or "data-language-name" in attributes or "data-shortcut-label" in attributes
                   or any(skip for _, skip in self.stack))
        if not blocked:
            for name in ("title", "aria-label", "placeholder"):
                if attributes.get(name):
                    self.add(attributes[name])
        if tag not in ("area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"):
            self.stack.append((tag, blocked))

    def handle_endtag(self, tag):
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index][0] == tag:
                del self.stack[index:]
                break

    def handle_data(self, data):
        if not any(skip for _, skip in self.stack):
            self.add(data)


def source_messages():
    keys = set()
    manifest = load_manifest()
    for name in (item["path"] for item in manifest["web"] if item.get("localize")):
        source = (EDITOR / name).read_text(encoding="utf-8")
        keys.update(json.loads(match[1]) for match in JS_REFERENCE.finditer(source))
    # Worker diagnostics are translated at the UI boundary with KfpsI18n.error.
    for name in (item["path"] for item in manifest["web"] if item.get("localize_errors")):
        source = (EDITOR / name).read_text(encoding="utf-8")
        keys.update(json.loads(match[1]) for match in re.finditer(
            r'(?:failure|new Error)\(\s*("(?:\\.|[^"\\])*")', source))
    native = native_source("host", ROOT)
    tree = ast.parse(native.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        positions = (0,) if node.func.attr in ("tr", "message", "_show_failure") else (1, 2) if node.func.attr == "_message_box" else ()
        for position in positions:
            if len(node.args) > position and isinstance(node.args[position], ast.Constant) and isinstance(node.args[position].value, str):
                keys.add(node.args[position].value)
    static = StaticMessages()
    static.feed((EDITOR / "index.html").read_text(encoding="utf-8"))
    return keys | static.keys


class MarkupContract(HTMLParser):
    def __init__(self, text):
        super().__init__(convert_charrefs=True)
        self.elements = Counter()
        self.feed(text)

    def handle_starttag(self, tag, attrs):
        # Translators can move emphasis, but must not change controls, links or IDs.
        structural = tuple(sorted((key, value) for key, value in attrs
                                  if key not in ("title", "aria-label", "placeholder")))
        self.elements[(tag, structural)] += 1


def validate(catalogs, allow_missing=False):
    errors = []
    english = catalogs["en"]
    for language, catalog in catalogs.items():
        if catalog.get("locale") != language:
            errors.append(f"{language}.json: incorrect locale metadata")
    for section in SECTIONS:
        keys = set(english.get(section, {}))
        for language, catalog in catalogs.items():
            entries = catalog.get(section, {})
            if set(entries) != keys:
                errors.append(f"{language}.{section}: keys differ from en.json; run sync")
            for key, value in entries.items():
                if not isinstance(value, str) or (not value and (language == "en" or not allow_missing)):
                    errors.append(f"{language}.{section}: missing translation: {key!r}")
                    continue
                if not value:
                    continue
                slots = lambda text: set(re.findall(r"\{(\d+)\}", text))
                omitted = set(map(str, catalog.get("pluralOmissions", {}).get(key, []))) if language == "ko" else set()
                if slots(value) != slots(key) - omitted:
                    errors.append(f"{language}.{section}: placeholder mismatch: {key!r}")
                if section in ("html", "messages") and re.search(r"<[a-z]", key):
                    if MarkupContract(key).elements != MarkupContract(value).elements:
                        errors.append(f"{language}.{section}: HTML structure/attributes differ: {key!r}")
    for key in sorted(source_messages() - set(english["messages"])):
        errors.append(f"New UI text: {key!r}; run sync and translate")
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("sync", "build", "check"))
    parser.add_argument("--allow-missing", action="store_true", help="Allow untranslated Korean drafts to fall back to English (not for CI).")
    args = parser.parse_args()
    catalogs = {language: read_catalog(language) for language in LANGUAGES}
    if args.command == "sync":
        for section in SECTIONS:
            keys = set().union(*(catalog[section] for catalog in catalogs.values()))
            if section == "messages":
                keys.update(source_messages())
            for key in sorted(keys):
                catalogs["en"][section].setdefault(key, key.replace("_", " ") if section == "families" else key)
                catalogs["ko"][section].setdefault(key, "")
        for language, catalog in catalogs.items():
            write_catalog(language, catalog)
        missing = sum(not value for section in SECTIONS for value in catalogs["ko"][section].values())
        print(f"Catalogs synchronized without deleting keys. {missing} Korean entries need translation.")
        return 0
    errors = validate(catalogs, args.allow_missing)
    if errors:
        print("\n".join(errors))
        return 1
    for language, catalog in catalogs.items():
        target = HERE / f"{language}.js"
        expected = pack(language, catalog)
        if args.command == "build":
            target.write_text(expected, encoding="utf-8", newline="\n")
        elif not target.exists() or target.read_text(encoding="utf-8") != expected:
            errors.append(f"{target.name} is stale; run locales/manage.py build")
    if errors:
        print("\n".join(errors))
        return 1
    print(f"English/Korean catalogs {args.command}: source keys, placeholders, HTML contracts and offline packs passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
