"use strict";
const assert = require("node:assert/strict");
const {create,equal} = require("../editor-history.js");
let at=0;
const store=create({limit:80,now:()=>at,timestamp:()=>"test"});
const shape={editor_id:"a",data:[0,0,1,1,0],color:[1,2,3,255]};
const snap=x=>({shapes:[{...shape,data:[x,0,1,1,0]}],editor_guides:null,editor_collapsed_groups:[]});
const base=store.installBaseline(snap(0),"load",true);
assert.equal(store.floor,0);
assert.equal(store.commit({...base}),false);
assert.equal(equal(base,{...base,shapes:[{...base.shapes[0]}]}),false,"Preserve record identity, not approximate pixel equality");
store.commit(snap(1),"nudge");
at=100;store.commit(snap(2),"nudge");
assert.equal(store.entries.length,2);
assert.equal(store.acceptRestore(0,base),true);
assert.equal(store.current(),base,"Undo must recover saved-content identity");
assert.ok(store.sequence>1,"Causal sequence must not define saved equality");
store.commit(snap(3),"shape");
assert.equal(store.entries.length,2,"Editing after undo truncates redo");
assert.equal(store.acceptRestore(0,snap(0)),false,"Reject stale restore target");
for(let i=0;i<150;i++)store.commit(snap(i),"shape");
assert.equal(store.entries.length,80);
assert.equal(store.floor,0);
assert.equal(store.index,79);
assert.ok(Object.isFrozen(store.entries));
assert.ok(store.estimate().bytes>0);
store.reset();
assert.equal(store.current(),null);assert.equal(store.floor,-1);
store.installBaseline(snap(0),"blank",false);
assert.equal(store.floor,-1);
console.log("editor-history: identity, coalescing, protected floor, retention, branch and stale restore passed");
